# Generated by Django 5.1.7 on 2025-05-28 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_chapter_options_chapter_chapter_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reviews_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('comments_count', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('blocks_count', models.IntegerField(default=0)),
                ('avg_comment_likes', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_snapshots', to='book.book')),
            ],
            options={
                'unique_together': {('book', 'date')},
            },
        ),
    ]
