# Generated by Django 5.1.7 on 2025-03-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_actions', '0002_rename_favoritegroup_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='date',
        ),
    ]
