# Generated by Django 5.1.7 on 2025-05-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='text',
            field=models.TextField(default='subject of thread'),
        ),
    ]
