# Generated by Django 5.1.7 on 2025-05-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/images/%Y/%m/%d/'),
        ),
    ]
