# Generated by Django 5.1.7 on 2025-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, upload_to='books/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
