# Generated by Django 5.1.7 on 2025-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['book', 'chapter_num']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
