# Generated by Django 5.1.7 on 2025-03-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default=None, upload_to='users/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
